version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # This will install Python 3.9 on the environment
    commands:
      - echo "=== Check if Python and AWS CLI were installed successfully ==="
      - python --version
      - aws --version
      - echo "=== CHECK CFN-LINT ==="
      - pip install cfn-lint  # Install cfn-lint
      - cfn-lint --version

  pre_build: # Check if your environment has all tools
    commands:
      - echo "=== CHECK FOR SYNTAX ON OUR TEMPLATES ==="
      - cfn-lint pipeline_us-east-1-ec2.yaml
      - echo "=== BUILD OUR CLOUDFORMATION ==="
      - aws cloudformation package --template-file pipeline_us-east-1-ec2.yaml  --s3-bucket patartifactbucket --output-template-file build-artifact.yaml --region us-east-1 --debug
     

  build:
    commands:
      - echo "=== RUN YOUR CODE HERE ==="
      - python my_app.py # RUN A PYTHON CODE

  post_build:
    commands:
      - echo "=== THIS IS MY POSTBUILD SECTION ==="
      - echo "Build completed on `date`..." # TELL THE USER WHEN THE BUILD IS COMPLETE

artifacts:
  files:
    - build-artifact.yaml
    
  